### PR TITLE
Blog Post: A Guide to IPFS Connectivity in Web Browsers

### PR DESCRIPTION
**Pull request by TheDiscordian**
This is a blog post to help assist people in getting started using browser js-ipfs. I linked the original HackMD here as some features I wasn't entirely sure how I should move them over (namely Table of Contents, and the little info boxes), I tried to keep it looking nice anyways :).

I set the date for June 21 as I wasn't sure what I should set.

Repo For Website: https://github.com/TheDiscordian/browser-ipfs-chat
Gist for Python script: https://gist.github.com/TheDiscordian/51962fea72f8d5a5c3bba79dd7009e1c
Original HackMD: https://hackmd.io/@Discordian/S1gBLg5Id/edit

Edit: P.S. No idea why the user shows up as one of my old accounts, redstarcoder.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@autonome Is this the post we discussed?

**Comment by autonome** [comment]
yep

**Comment by TheDiscordian** [comment]
It seems I forgot to add in a line explaining how to actually *use* Certbot to get a certificate. Please hold off potentially accepting until I update it :).

**Comment by jessicaschilling** [comment]
@TheDiscordian Drop a note here when you're done - thanks!

**Comment by jessicaschilling** [comment]
@autonome Any reason why this shouldn't also be a page on docs.ipfs.io? Feels like we should have a more permanent and less "published in a blog stream" instantiation of this content.

**Comment by autonome** [comment]
Yeah there could be a docs version of this, would likely need to be more
conceptual/referential. File an issue!

**Comment by jessicaschilling** [comment]
@TheDiscordian - Quick note that I've given you write access to this repo: we discovered that without it, Forestry actually duplicates itself on the admin end. Shouldn't be materially different, though you may need to log back in to Forestry to make future changes to your post. LMK if you have any problems.

**Comment by jessicaschilling** [comment]
@TheDiscordian Is this ready for final review?

**Comment by TheDiscordian** [comment]
I'll commit the final version of what I have done in 1hr.

Was discussing potentially waiting for a docker-compose script. However not
sure if it's worth waiting. (I think it could be added in later if needed?)

@dietrich do you think we should wait for the other team to give it a look
over? I think as-is should be fine. Finally get this thing live :p.

**Comment by TheDiscordian** [comment]
@jessicaschilling can you add therealdiscordian@gmail.com to the Forestry org please? Seems using different emails confuses Forestry for which Github acc I want to use (which is why it was trying to use redstarcoder), so I just made a new one.

**Comment by autonome** [comment]
I haven't gotten any suggestions for better ways of doing the Docker bit,
so let's ship it as-is.

**Comment by jessicaschilling** [comment]
@TheDiscordian Added you as a Forestry user under the email you specified, and removed the other one. I'll have a closer look at the post itself later today - thanks!

**Comment by TheDiscordian** [comment]
@jessicaschilling thanks, and sorry for the inconvenience! I appear to still be having some issues getting Forestry rolling again ... maybe I should just try to commit an MD? I can see the ipfs/ipfs-blog repo, but I get this error when trying to add it to Forestry:

image

**Comment by jessicaschilling** [comment]
@TheDiscordian I merged all of this into `staging` to get it out of your fork — what's messing up the process is that you're working out of a fork and Forestry is only set up to work out of `staging` (or it was until your fork somehow cloned the entire Forestry instance, which we've since deleted).

Can you try clearing your caches or using a private tab and just re-authing at https://app.forestry.io/login using therealdiscordian@gmail.com? That should get you hooked up with the `staging` Forestry instance.

**Comment by TheDiscordian** [comment]
> @TheDiscordian If things get really borky, we can hop on a video call and try to troubleshoot.

I've tried 2 browsers, private and not private, same issue :'). Yes that'd be awesome, could we possibly schedule that call for tomorrow before 3pm EST? (If today's better I'll work around)

**Comment by jessicaschilling** [comment]
Sent you an invitation - in the meantime, mind a look at https://github.com/ipfs/ipfs-blog/pull/244 for any final tweaks? Would be great to get this published today!

**Pull request merged**
