### PR TITLE
feat: add outbound link icon to cards

### LINKED ISSUE #213: Improve the UX of external card links
Currently it's not possible to distinguish external links from internal links on the blog homepage cards and it can be disorienting when these links open in a new tab. This UX is also inconsistent with the blog body content which displays a small external arrow for any outbound links.
 
2021-05-24 at 12 29 10

Example from Protocol.ai

2021-05-24 at 12 26 51

### PR DESCRIPTION
**Pull request by jdiogopeixoto**
- Adds the `<OutboundLink />` icon for the external links inside the cards
- Keeps the CSS `line-clamp` for the internal links

Closes #213

### CODE REVIEW

**Review by jessicaschilling — APPROVED** [review]
LGTM, though I'll defer to @cwaring before merging. Thank you!

**Comment by cwaring** [comment]
Thanks @jdiogopeixoto. This looks like a lot of unnecessary processing, can we not achieve the same result with css? Possibly `text-overflow: ellipsis;` https://tailwindcss.com/docs/text-overflow

**Comment by jdiogopeixoto** [comment]
@cwaring I don't think we can use `text-overflow: ellipsis;` to truncate the text on the third line, we need `line-clamp` for that.

The issue with the `line-clamp` is that if I simply add the icon to the end of the text, and the text is too long (more than 3 lines), the icon stays hidden. 

Also to prevent the [point 2](https://github.com/ipfs/ipfs-blog/issues/213#issuecomment-847460346) mentioned in the issue we need to group the last word with the icon, so they wrap together. 

I might be missing something but I tried a lot of different solutions and even talked with @jessicaschilling about adding the icon somewhere else inside the card, but this is the solution we came up with and agreed on.

**Comment by cwaring** [comment]
@jdiogopeixoto @jessicaschilling I sketched out another idea in #220 that is more lightweight, lmk if that works (also feel free to refactor).

**Pull request closed without merging**
