### PR TITLE
Add blog: HNS

### PR DESCRIPTION
**Pull request by emilymvaughan**

### CODE REVIEW

**Comment by stan-pl** [comment]
@andyschwab Can you take a look at this issue with preview/Fleek/publishing please? We've been trying to publish this post from Forestry since yesterday. Thanks!

**Comment by andyschwab** [comment]
@stan-pl @emilymvaughan - looks like this is working again. Can you check to ensure the preview is as you expected? The bug appeared to be snippet code related to YouTube. It looks like the IPFS site was using the same snippet format as the Filecoin site, but they are actually two different platforms - so the code was breaking things in the IPFS build. You can see the YouTube code I replaced the snippet data with in the two files.

**Comment by emilymvaughan** [comment]
Ahhh I see, good to know for future reference @stan-pl !

**Comment by stan-pl** [comment]
Yes good to know, thanks @andyschwab

**Pull request merged**
