### PR TITLE
Publishing Chainlink hackathon recap 

### PR DESCRIPTION
**Pull request by jennwrites**
Not sure what else is on this branch atm but tentatively raising a hand that I'd like to publish this post. 😬

### CODE REVIEW

**Comment by jennwrites** [comment]
Uh oh, the YouTube embeds didn't render. Can someone help?

**Comment by jessicaschilling** [comment]
@jennwrites - I fixed the video embeds, but in future you can find the syntax to use here: https://github.com/ipfs/ipfs-blog#forestry-authoringediting-tips

**Comment by jennwrites** [comment]
Ah, sorry I missed that part (and it's so easy 🤦‍♀️ )! Thanks @jessicaschilling

**Comment by jessicaschilling** [comment]
@jennwrites No worries - this syntax is also nicer because it auto-sizes the video based on the user's viewport.

**Pull request merged**
