### PR TITLE
chore: add workflow for automatic image compression on PR

### PR DESCRIPTION
**Pull request by zebateira**
Partially addresses #84

This PR adds integration with [Image Actions](https://github.com/marketplace/actions/image-actions) to enable automatic image compression when a new PR is added.

So when the PR from staging is created with the new forestry changes, images will be automatically compress in the PR.

### CODE REVIEW

**Review by jdiogopeixoto — APPROVED** [review]
This is cool. Good job! 👏

**Comment by jessicaschilling** [comment]
Thanks @zebateira! Added @cwaring as a reviewer.

**Comment by cwaring** [comment]
Nice. Some of those saving are pretty big, as it is re-processing in a destructive mode we need to be a bit careful as it is introducing a lot of compression artefacts.

- [original](https://blog.ipfs.io/assets/img/107-nix-ipfs-header-image.ef0ead87.jpg)
2021-04-12 at 17 29 57

- [processed](https://raw.githubusercontent.com/ipfs/ipfs-blog/f7d47cd65f0f2b1cf7b89276b55ff4d045275705/src/assets/107-nix-ipfs-header-image.jpg)
2021-04-12 at 17 30 14

A few thoughts:
- How long did take to run across the src dir?
(I'd prefer if it only touched new files to save build time but perhaps the actions keeps some kind of index as a cache?)
- If I make a commit without images will is still attempt to optimise?
- Is is possible to configure it to run on pre-merge as a last step?
- Is there an action that can process images in a less destructive mode? (similar to [ImageOptim](https://imageoptim.com/mac))

**Comment by zebateira** [comment]
@cwaring ouch, indeed some images are dreadful now.

> How long did take to run across the src dir?

It was fast and it didn't block the preview so I think we need to worry about that.

> If I make a commit without images will is still attempt to optimise?

I don't think so, but I'll test this (it has a regex for only running it if the changes include images in the assets directory)

> Is is possible to configure it to run on pre-merge as a last step?

I think it would be more beneficial to have it on push so that we see the real final result in the preview.

**Comment by cwaring** [comment]
Great, because we are lazy-loading all the images I'd prefer not to over compress. I ran ImageOptim over the original assets dir and that saved about 75% in a lossless way.

**Comment by zebateira** [comment]
I bumped the quality setting to 100% so we get lossless compression. Also reverted the previous compressions and the latest compressions do not seem to have lost any quality.

Unfortunately this action does not allow to only compress the images that were changed in the PR. Issue here: https://github.com/calibreapp/image-actions/issues/92
For now it takes roughly 1/2 minutes to run on all of our images. It will clearly increase over time, and so will the build time.

We do have the [ImageOptim CLI](https://github.com/JamieMason/ImageOptim-CLI), so in the future we can create an action that uses it and runs only on the changed images of the PR. If they don't implement it in the calibreapp/image-actions in the meanwhile.

I suggest waiting and see if they implement it, and in the meantime if we get the change, we can simply create an action ourselves.
What do you think @cwaring?

**Comment by karlhorky** [comment]
> We do have the [ImageOptim CLI](https://github.com/JamieMason/ImageOptim-CLI), so in the future we can create an action that uses it and runs only on the changed images of the PR. If they don't implement it in the calibreapp/image-actions in the meanwhile.

If you end up doing this, do you think that you could report back to the issue in https://github.com/calibreapp/image-actions/issues/92 ?

**Comment by zebateira** [comment]
@karlhorky will do!

**Comment by jessicaschilling** [comment]
@cwaring, just checking in with you on this. Thanks!

**Comment by cwaring** [comment]
@zebateira would you mind dropping some notes here from Slack discussion. 🙏🏻

**Comment by zebateira** [comment]
> @zebateira would you mind dropping some notes here from Slack discussion. 🙏🏻

Yap!

> John has also been working on a custom ci image compression script for the docs: https://github.com/filecoin-project/filecoin-docs/pull/793/files
this one however only operates on images that are part of the commit range

This would be good to purse, considering the potential to spin this off into a separate github action that we could use across content heavy sites, but taking into account our bandwidth, I think we'll keep the implementation above, and then update in the future if necessary.

**Pull request merged**
