### PR TITLE
Setup speedcurve script

### LINKED ISSUE #84: Add performance instrumentation to ongoing metrics
Per @atopal request, we need to add some form of site performance instrumentation to (at minimum) the primary IPFS websites going forward:
- New blog.ipfs.io
- Existing blog.ipfs.io (this may simply be some sort of baseline measurement, considering we are so close to relaunch)
- Existing ipfs.io (for comparison purposes)
- Replatformed ipfs.io
- docs.ipfs.io

Kicking this work off in this repo, since we're already doing a lot of pre-launch work on the blog.

@zebateira: Can you please research potential approaches? Some notes:
- @atopal is partial to [SpeedCurve](https://speedcurve.com/), but it's a commercial service with whom we don't currently have an account, so we should evaluate the larger landscape
- This is likely to scale to all PL websites, so a larger scope may be a cost consideration if we utilize a commercial service
- Data would be repurposed in our reporting dashboards, so bonus points for a programmatic way of getting it into Observable

@atopal: Please edit this comment or add additional comments for any other specs or notes. I'm tentatively labeling this as P2, on the assumption that it's acceptable to work on this post-blog-launch **as long as payload problems in https://github.com/ipfs/ipfs-blog/issues/41 are resolved for launch** — but please revise if you feel this is needed sooner.

cc @terichadbourne @johnnymatthews @yusefnapora @johndmulhausen for context and/or discussion.

### PR DESCRIPTION
**Pull request by zebateira**
Partially addresses #84

### CODE REVIEW

**Comment by cwaring** [comment]
I appreciate the effort setting this up however it makes me a little concerned that we're sending more user data to a 3rd party service, and we may also need to evaluate for GDPR in Europe. Given the effort we've made to migrate to our own countly instance for privacy and feedback we've had from many users I really believe we should evaluate if this is necessary.

Personally I'd prefer to performance test our sites externally from a remote cluster tool as this app is 100% static and distributed via a CDN the probability of bottlenecks (that we can actually fix) is very low.

cc: @atopal @jessicaschilling

**Comment by jessicaschilling** [comment]
This one is @atopal's requirement - I defer to whatever he decides.

**Comment by cwaring** [comment]
To add some additional context here there have been many discussions about intentionally removing external dependancies, both for privacy and performance so I believe that should be out default stance wherever possible. This is echoing Juan's sentiment also ensuring that projects can live self contained on IPFS indefinitely.

**Comment by atopal** [comment]
Those are valid concerns for sure and there are [some options we have](https://support.speedcurve.com/en/articles/3378439-can-lux-js-be-self-hosted) when it comes to security and privacy. That said, [According to Speedcurve](https://support.speedcurve.com/en/articles/1707704-what-data-is-collected-by-lux-for-rum) RUM "does not gather any personally identifiable information (PII) such as IP addresses, names, emails, or other metrics that could identify a user", and here's their [statement on GDPR compliance](https://support.speedcurve.com/en/articles/2044623-data-protection-gdpr-compliance-at-speedcurve). I don't know what our policies are re legal audits, but at Mozilla I've had to submit our usage for legal, privacy and security review and we didn't see any blockers. 

Unfortunately there is really no alternative to using real user metrics to understand what your audience is experiencing. We don't know whether they are on slow computers/smartphones or slow connections, whether they have latency or bandwidth issues. 

Re self contained on IPFS: This doesn't add any user facing functionality, and I don't know how useful it would be on IPFS, I don't think it violates that sentiment.

My suggestion would be that we continue, but review after 30 days and 90 days whether this is providing enough value to continue using it.

**Comment by cwaring** [comment]
Countly also has a level of [performance reporting](https://support.count.ly/hc/en-us/articles/900000819806-Performance-Monitoring), combined with lighthouse at a CI level I believe that would be a more friendly and integrated solution for a static website. Additionally considering the [monthly cost of Speedcurve](https://speedcurve.com/pricing/).

However I'm not the PM for this project so happy to pass the baton on this one 😎

**Comment by atopal** [comment]
Yes, let's go ahead for now. I'll also request we switch to the small plan, if we're not on it already.

**Pull request merged**
