### PR TITLE
fix: add social-card.png to public image directory

### PR DESCRIPTION
**Pull request by jessicaschilling**
We're getting 404s on the generic social card in Countly:
image

This PR adds that image to the top-level public images directory on the theory that it'll always display and not be impacted by the random numbers that get added to image URLs on site build.

@zebateira, does this sound like the right approach?

### CODE REVIEW

**Comment by zebateira** [comment]
We have a plugin to take care of this I believe: https://github.com/ipfs/ipfs-blog/tree/main/src/.vuepress/plugins/vuepress-plugin-og-image

cc @cwaring 

It seems that for some reason the final page metadata with the fixed URLs are not persisted somehow? I ran the build locally and the plugin is running and fixing the urls correctly.

**Comment by zebateira** [comment]
Ah, the final build indeed includes the correct urls with cache bust, so that's why it is working properly as we can see in metatags.io and in social media cards (the urls requested of the images include cache bust.

**Comment by jessicaschilling** [comment]
That makes sense. Any suggestions other than just "live with it"? Not sure if this is worth the effort of working hard to fix.

**Comment by zebateira** [comment]
> That makes sense. Any suggestions other than just "live with it"? Not sure if this is worth the effort of working hard to fix.

let's see if @cwaring has an idea of what we can do here.

**Comment by zebateira** [comment]
Let's merge this fix as is since it will fix some edge cases.

**Pull request merged**
