### PR TITLE
post: A guide to IPFS connectivity in browsers

### PR DESCRIPTION
**Pull request by jessicaschilling**
Starts with @TheDiscordian's https://github.com/ipfs/ipfs-blog/pull/233 PR and adds the following:
- Copy edits (mainly standards from https://docs.ipfs.io/community/contribute/grammar-formatting-and-style/)
- Clarity edits

### CODE REVIEW

**Comment by TheDiscordian** [comment]
> @TheDiscordian If you're OK with just making changes in GitHub's code suggestions, that works and you can bypass Forestry this time. Otherwise fire up a call with the link from tomorrow's meeting invite and Zoom will nudge me that someone's in my room.

Cheers, tomorrow works then, I'll focus on just using git directly! Shouldn't be too long!

**Comment by TheDiscordian** [comment]
@jessicaschilling I believe I have all the latest changes in, and it looks ready for final look-over :pray: .

**Comment by TheDiscordian** [comment]
@jessicaschilling I believe I have all the latest changes in, and it looks ready for final look-over :pray: .

**Review by TheDiscordian — APPROVED** [review]

**Comment by jessicaschilling** [comment]
@TheDiscordian Agreed, but alas Forestry is auto-"fixing" this — that said, I'd like to publish a minimally edited version of this content in the IPFS docs (PR forthcoming) and we can use official formatting there 😊

**Comment by TheDiscordian** [comment]
@jessicaschilling I think that sounds like a good idea as well! @autonome and I were thinking both sounded like a good idea, I'm down with whatever works best :+1:

**Comment by jessicaschilling** [comment]
Merged - thanks @TheDiscordian and @autonome! Will name-check you in a related docs PR.

**Pull request merged**
